# Generated by Django 5.1.4 on 2024-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date_start', models.DateField()),
                ('transaction_date_end', models.DateField()),
                ('business_facility', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('business_facility', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('co2_item', models.FloatField()),
            ],
        ),
    ]
